<a href="https://colab.research.google.com/github/ajaykumar080286/PyTorch/blob/main/2_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


**Creating a Tensor**

In [3]:
# using empty

a=torch.empty(2,3)

In [4]:

# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.1054, 0.3679, 0.5300],
        [0.9675, 0.5815, 0.8880]])

In [8]:
#manual_seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
# using tensor

In [10]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [11]:
#other ways
print("Using arange", torch.arange(10))

print("Using linspace", torch.linspace(1,5,10))

print("Using eye", torch.eye(5))


print("Using full", torch.full((3,3),5))




Using arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])
Using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [22]:
x=torch.tensor([[2,3,4],[1,2,3]], dtype=torch.float32)

In [23]:
x.shape

torch.Size([2, 3])

In [24]:
y=torch.empty_like(x)

In [25]:
y.shape

torch.Size([2, 3])

In [26]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.rand_like(x)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

**Tensor Data Types**

In [30]:
x.dtype

torch.float32

In [31]:
torch.tensor([1,2,3],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
x.to(torch.int32)

tensor([[2, 3, 4],
        [1, 2, 3]], dtype=torch.int32)

Data Type

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


**Mathematical operations**

In [35]:
#1. Scalar operation

In [36]:
x=torch.rand(2,2)

In [37]:
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [38]:
# addition
x+2

tensor([[2.2666, 2.6274],
        [2.2696, 2.4414]])

In [39]:
# substraction
x-2

tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])

In [47]:
# Multi
x*2

tensor([[0.5332, 1.2549],
        [0.5393, 0.8827]])

In [48]:
x*100

tensor([[26.6580, 62.7449],
        [26.9632, 44.1364]])

In [50]:
# division
x/3

tensor([[0.0889, 0.2091],
        [0.0899, 0.1471]])

In [43]:
(x*100)//3

tensor([[ 8., 20.],
        [ 8., 14.]])

In [45]:
((x*100)//3)%3

tensor([[2., 2.],
        [2., 2.]])

In [51]:
# power
x**2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

In [52]:
### 2. Element wise operation


In [53]:
a = torch.rand(2,3)
b = torch.rand(2,3)


In [54]:
a+b

tensor([[0.8441, 0.8378, 1.0569],
        [0.3448, 1.2448, 0.7826]])

In [55]:
a-b

tensor([[-0.2503,  0.8255, -0.8462],
        [ 0.1942, -0.5272, -0.3838]])

In [56]:
a*b

tensor([[0.1625, 0.0051, 0.1002],
        [0.0203, 0.3179, 0.1163]])

In [57]:
a/b

tensor([[5.4263e-01, 1.3500e+02, 1.1068e-01],
        [3.5806e+00, 4.0497e-01, 3.4184e-01]])

In [58]:
a**2

tensor([[0.0882, 0.6917, 0.0111],
        [0.0726, 0.1287, 0.0397]])

In [59]:
c = torch.tensor([1, -2, 3, -4])

In [60]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [61]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [62]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [63]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [64]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [65]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [66]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**3. Reduction operation**

In [67]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [68]:
e

tensor([[3., 4., 9.],
        [6., 2., 0.]])

In [69]:
#sum of matrix

In [70]:
torch.sum(e)

tensor(24.)

In [71]:
torch.sum(e,dim=0)

tensor([9., 6., 9.])

In [73]:
torch.sum(e,dim=1)

tensor([16.,  8.])

In [74]:
torch.min(e)

tensor(0.)

In [75]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 3.0000, 4.5000])

In [76]:
# median
torch.median(e)

tensor(3.)

In [77]:
# product
torch.prod(e)

tensor(0.)

In [78]:
# standard deviation
torch.std(e)

tensor(3.1623)

In [79]:
# variance
torch.var(e)

tensor(10.)

In [80]:
# argmax
torch.argmax(e)

tensor(2)

In [81]:
# argmin
torch.argmin(e)

tensor(5)

**4. Matrix operations**

In [84]:
f=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g=torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)

In [85]:
print(f)

print(g)

tensor([[0., 9., 6.],
        [9., 5., 4.]])
tensor([[8., 8.],
        [6., 0.],
        [0., 0.]])


In [86]:
# matrix multiplcation

In [87]:
torch.matmul(f,g)

tensor([[ 54.,   0.],
        [102.,  72.]])

In [88]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [90]:
f

tensor([[0., 9., 6.],
        [9., 5., 4.]])

In [94]:
torch.transpose(f, 0, 1)

tensor([[0., 9.],
        [9., 5.],
        [6., 4.]])

In [96]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 1., 3.],
        [0., 1., 1.],
        [7., 9., 4.]])

In [97]:
# determinant
torch.det(h)

tensor(-14.0000)

In [98]:
# inverse
torch.inverse(h)

tensor([[ 0.3571, -1.6429,  0.1429],
        [-0.5000,  1.5000,  0.0000],
        [ 0.5000, -0.5000,  0.0000]])

**### 5. Comparison operations**

In [99]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 8, 9],
        [3, 7, 8]])
tensor([[1, 4, 1],
        [6, 3, 2]])


In [100]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

In [102]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 9., 8.],
        [5., 3., 7.]])

In [103]:
torch.log(k)

tensor([[  -inf, 2.1972, 2.0794],
        [1.6094, 1.0986, 1.9459]])

In [104]:
torch.exp(k)

tensor([[1.0000e+00, 8.1031e+03, 2.9810e+03],
        [1.4841e+02, 2.0086e+01, 1.0966e+03]])

In [105]:
torch.sqrt(k)

tensor([[0.0000, 3.0000, 2.8284],
        [2.2361, 1.7321, 2.6458]])

In [106]:
torch.sigmoid(k)

tensor([[0.5000, 0.9999, 0.9997],
        [0.9933, 0.9526, 0.9991]])

In [107]:
# relu
torch.relu(k)

tensor([[0., 9., 8.],
        [5., 3., 7.]])

In [109]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0067, 0.9975, 0.7311],
        [0.9933, 0.0025, 0.2689]])

**Inplace Operations**

In [108]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])
tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])


In [110]:
m+n

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [111]:
m.add_(n)

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [113]:
m

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [114]:
n

tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])

In [115]:
torch.relu(m)

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [116]:
m.relu_()

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [117]:
m

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

**Copying a Tensor**

In [118]:
a = torch.rand(2,3)
a

tensor([[0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [119]:
b = a

In [120]:
b

tensor([[0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [121]:
a[0][0]=0

In [122]:
a

tensor([[0.0000, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [123]:
b

tensor([[0.0000, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [124]:
id(a)

132161814029456

In [125]:
id(b)

132161814029456