<a href="https://colab.research.google.com/github/ajaykumar080286/PyTorch/blob/main/2_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


**Creating a Tensor**

In [3]:
# using empty

a=torch.empty(2,3)

In [4]:

# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.3444, 0.5953, 0.1513],
        [0.3260, 0.1539, 0.4023]])

In [8]:
#manual_seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
# using tensor

In [10]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [11]:
#other ways
print("Using arange", torch.arange(10))

print("Using linspace", torch.linspace(1,5,10))

print("Using eye", torch.eye(5))


print("Using full", torch.full((3,3),5))




Using arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using linspace tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])
Using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [12]:
x=torch.tensor([[2,3,4],[1,2,3]], dtype=torch.float32)

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
y=torch.empty_like(x)

In [15]:
y.shape

torch.Size([2, 3])

In [16]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.rand_like(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

**Tensor Data Types**

In [19]:
x.dtype

torch.float32

In [20]:
torch.tensor([1,2,3],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
x.to(torch.int32)

tensor([[2, 3, 4],
        [1, 2, 3]], dtype=torch.int32)

Data Type

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


**Mathematical operations**

In [23]:
#1. Scalar operation

In [24]:
x=torch.rand(2,2)

In [25]:
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [26]:
# addition
x+2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [27]:
# substraction
x-2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [28]:
# Multi
x*2

tensor([[1.7388, 1.1354],
        [1.4822, 0.8588]])

In [29]:
x*100

tensor([[86.9404, 56.7715],
        [74.1094, 42.9404]])

In [30]:
# division
x/3

tensor([[0.2898, 0.1892],
        [0.2470, 0.1431]])

In [31]:
(x*100)//3

tensor([[28., 18.],
        [24., 14.]])

In [32]:
((x*100)//3)%3

tensor([[1., 0.],
        [0., 2.]])

In [33]:
# power
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

In [34]:
### 2. Element wise operation


In [35]:
a = torch.rand(2,3)
b = torch.rand(2,3)


In [36]:
a+b

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

In [37]:
a-b

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

In [38]:
a*b

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

In [39]:
a/b

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

In [40]:
a**2

tensor([[0.7840, 0.3294, 0.0711],
        [0.3937, 0.0727, 0.1948]])

In [41]:
c = torch.tensor([1, -2, 3, -4])

In [42]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [45]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [46]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [47]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [48]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**3. Reduction operation**

In [49]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [50]:
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [51]:
#sum of matrix

In [52]:
torch.sum(e)

tensor(32.)

In [53]:
torch.sum(e,dim=0)

tensor([ 7., 14., 11.])

In [54]:
torch.sum(e,dim=1)

tensor([18., 14.])

In [55]:
torch.min(e)

tensor(0.)

In [56]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 7.0000, 5.5000])

In [57]:
# median
torch.median(e)

tensor(5.)

In [58]:
# product
torch.prod(e)

tensor(0.)

In [59]:
# standard deviation
torch.std(e)

tensor(3.7238)

In [60]:
# variance
torch.var(e)

tensor(13.8667)

In [61]:
# argmax
torch.argmax(e)

tensor(1)

In [62]:
# argmin
torch.argmin(e)

tensor(3)

**4. Matrix operations**

In [63]:
f=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g=torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)

In [64]:
print(f)

print(g)

tensor([[3., 4., 9.],
        [6., 2., 0.]])
tensor([[6., 2.],
        [7., 9.],
        [7., 3.]])


In [65]:
# matrix multiplcation

In [66]:
torch.matmul(f,g)

tensor([[109.,  69.],
        [ 50.,  30.]])

In [67]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [68]:
f

tensor([[3., 4., 9.],
        [6., 2., 0.]])

In [69]:
torch.transpose(f, 0, 1)

tensor([[3., 6.],
        [4., 2.],
        [9., 0.]])

In [70]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [71]:
# determinant
torch.det(h)

tensor(-222.)

In [72]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

**### 5. Comparison operations**

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [74]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

In [75]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [76]:
torch.log(k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [77]:
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [78]:
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [79]:
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [80]:
# relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [81]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

**Inplace Operations**

In [82]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [83]:
m+n

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [84]:
m.add_(n)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [85]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [86]:
n

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [87]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [88]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [89]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

**Copying a Tensor**

In [90]:
a = torch.rand(2,3)
a

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [91]:
b = a

In [92]:
b

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [93]:
a[0][0]=0

In [94]:
a

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [95]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [96]:
id(a)

132329153088160

In [97]:
id(b)

132329153088160

**Tensor Operation in GPU**

In [98]:
torch.cuda.is_available()

True

In [99]:
device=torch.device("cuda")  # this tensor will create on GPU but previuos was created on RAM -CPU

In [100]:
device

device(type='cuda')

In [101]:
torch.rand((2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [102]:
#moving existing tensor to GPU
a=torch.rand(2,3) #cerated at CPU
a

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [103]:
b=a.to(device)  #preform on GPU

In [104]:
b+5

tensor([[5.3725, 5.7980, 5.8399],
        [5.1374, 5.2331, 5.9578]], device='cuda:0')

In [ ]:
import time
size=100000
# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")


**Reshape**

In [ ]:
a=torch.ones(4,4)

In [ ]:
a