<a href="https://colab.research.google.com/github/ajaykumar080286/PyTorch/blob/main/3_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**Reshape**

In [2]:
a=torch.ones(4,4)

In [3]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [6]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b=torch.rand(2,3,4)

In [8]:
b

tensor([[[0.5340, 0.0765, 0.8830, 0.3875],
         [0.6281, 0.0754, 0.0889, 0.4520],
         [0.3945, 0.7232, 0.8638, 0.7523]],

        [[0.5028, 0.8019, 0.6160, 0.5697],
         [0.5100, 0.4495, 0.0689, 0.0250],
         [0.8561, 0.3038, 0.4908, 0.9240]]])

In [9]:
#permute

In [11]:
b.permute(2,0,1)

tensor([[[0.5340, 0.6281, 0.3945],
         [0.5028, 0.5100, 0.8561]],

        [[0.0765, 0.0754, 0.7232],
         [0.8019, 0.4495, 0.3038]],

        [[0.8830, 0.0889, 0.8638],
         [0.6160, 0.0689, 0.4908]],

        [[0.3875, 0.4520, 0.7523],
         [0.5697, 0.0250, 0.9240]]])

In [12]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [14]:
#image size
c=torch.rand(226,226,3)

In [16]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [17]:
d=torch.rand(1,20)

In [18]:
d.squeeze(0).shape

torch.Size([20])

**Numpy & PyTorch**

In [19]:
import numpy as np


In [22]:
a=torch.tensor([1,2,3])

In [23]:
a

tensor([1, 2, 3])

In [24]:
b=a.numpy()

In [25]:
b

array([1, 2, 3])

In [26]:
c=np.array([1,2,3])

In [27]:
c

array([1, 2, 3])

In [28]:
torch.from_numpy(c)

tensor([1, 2, 3])