<a href="https://colab.research.google.com/github/ajaykumar080286/PyTorch/blob/main/6_pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [35]:
class Model(nn.Module):

  def __init__(self,num_feature):
    super().__init__()
    #decleare layer
    self.linear=nn.Linear(num_feature,1)
    #activation funcation
    self.sigmoid=nn.Sigmoid()

  def forward(self,feature):
    out=self.linear(feature)
    out=self.sigmoid(out)
    return out


In [36]:
# create dataset
features = torch.rand(10,5)
model=Model(features.shape[1])


In [37]:
model(features)

tensor([[0.5333],
        [0.4935],
        [0.5105],
        [0.5512],
        [0.4720],
        [0.5167],
        [0.5176],
        [0.5968],
        [0.5801],
        [0.5195]], grad_fn=<SigmoidBackward0>)

In [39]:
model.linear.weight

Parameter containing:
tensor([[ 0.2565, -0.4040, -0.1439, -0.3733,  0.0518]], requires_grad=True)

In [40]:
model.linear.bias

Parameter containing:
tensor([0.4366], requires_grad=True)

In [41]:
!pip install torchinfo

In [42]:
from torchinfo import summary


In [43]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00