<a href="https://colab.research.google.com/github/ajaykumar080286/PyTorch/blob/main/7_pytorch_training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn

In [33]:
#!pip install torchinfo

In [34]:
from torchinfo import summary

In [39]:
class Model(nn.Module):

  def __init__(self,num_feature):
    super().__init__()
    #decleare layer
    self.linear1=nn.Linear(num_feature,3) # Changed from 1 to 3
    self.relu=nn.ReLU()

    #activation funcation
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [40]:
# create dataset
features = torch.rand(10,5)
model=Model(features.shape[1])


In [41]:
model(features)


tensor([[0.5098],
        [0.4893],
        [0.4878],
        [0.5152],
        [0.5030],
        [0.5174],
        [0.4946],
        [0.4871],
        [0.4908],
        [0.4871]], grad_fn=<SigmoidBackward0>)

In [42]:
model.linear1.weight

Parameter containing:
tensor([[-0.4079, -0.4020, -0.2110, -0.1582,  0.1787],
        [ 0.3944, -0.3125,  0.3157,  0.3421,  0.0702],
        [ 0.1097, -0.0851,  0.1810,  0.4426, -0.0315]], requires_grad=True)

In [43]:
model.linear2.weight

Parameter containing:
tensor([[0.4414, 0.0100, 0.4373]], requires_grad=True)

In [44]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Container Sequential**

In [47]:
class Model1(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    #decleare layer
    self.network=nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [52]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model1(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6057],
        [0.6418],
        [0.6735],
        [0.6464],
        [0.6426],
        [0.7285],
        [0.6483],
        [0.6706],
        [0.5811],
        [0.6601]], grad_fn=<SigmoidBackward0>)

In [53]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 1]                   6
│    └─Sigmoid: 2-2                      [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [54]:
class Model1(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    #decleare layer
    self.network=nn.Sequential(
        nn.Linear(num_features, 1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [55]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model1(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5299],
        [0.5291],
        [0.5767],
        [0.5347],
        [0.4851],
        [0.4834],
        [0.5045],
        [0.4673],
        [0.5118],
        [0.4987]], grad_fn=<SigmoidBackward0>)